version: '3.8'

services:
  front:
    build: ./example-frontend
    container_name: front
    ports:
     - 5000:5000
  back:
    build: ./example-backend
    container_name: back
    ports:
     - 8080:8080
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis
    container_name: redis
