version: '3.8'

services:
  front:
    build: ./example-frontend
    container_name: front
    ports:
     - 5000:5000
  back:
    build: ./example-backend
    container_name: back
    ports:
     - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=password
  redis:
    image: redis
    container_name: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres