version: '3.8'

services:
  front:
    build: ./example-frontend
    container_name: front
    ports:
     - 5000:5000
    environment:
     - REACT_APP_BACKEND_URL=http://localhost/api/
  back:
    build: ./example-backend
    container_name: back
    ports:
     - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=password
  redis:
    image: redis
    container_name: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
  nginx:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    